# Generated by Django 5.2 on 2026-05-22 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('projects', '0002_alter_project_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='clients.client'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('discussion', 'Обсуждение'), ('active', 'В работе'), ('paused', 'На паузе'), ('done', 'Завершен')], default='discussion', max_length=20),
        ),
    ]
